import { v4 as uuid } from "uuid";

import img01 from "../../public/images/01.png";
import img02 from "../../public/images/02.png";
import img03 from "../../public/images/03.png";
import img04 from "../../public/images/04.png";
import img05 from "../../public/images/05.png";
import img06 from "../../public/images/06.png";
import img07 from "../../public/images/07.png";
import img08 from "../../public/images/08.png";
import img09 from "../../public/images/09.png";
import img10 from "../../public/images/10.png";
import img11 from "../../public/images/11.png";
import img12 from "../../public/images/12.png";
import img13 from "../../public/images/13.png";
import img14 from "../../public/images/14.png";
import img15 from "../../public/images/15.png";
import img16 from "../../public/images/16.png";
import img17 from "../../public/images/17.png";
import img18 from "../../public/images/18.png";
import img19 from "../../public/images/19.png";
import img20 from "../../public/images/20.png";
import {IProducts} from "../utilities/interfaces/interfaces";


export const productsDB: IProducts[] = [
  {
    id: uuid(),
    title: "Title 01",
    description: "Description 01",
    hot: false,
    sale: false,
    category: "dress",
    price: 63.85,
    oldPrice: null,
    image: img01,
  },
  {
    id: uuid(),
    title: "Title 02",
    description: "Description 02",
    hot: false,
    sale: true,
    category: "dress",
    price: 55.65,
    oldPrice: 63.85,
    image: img02,
  },
  {
    id: uuid(),
    title: "Title 03",
    description: "Description 03",
    hot: false,
    sale: false,
    category: "dress",
    price: 63.85,
    oldPrice: null,
    image: img03,
  },
  {
    id: uuid(),
    title: "Title 04",
    description: "Description 03",
    hot: false,
    sale: false,
    category: "t-shirt",
    price: 63.85,
    oldPrice: null,
    image: img04,
  },
  {
    id: uuid(),
    title: "Title 05",
    description: "Description 03",
    hot: true,
    sale: false,
    category: "dress",
    price: 63.85,
    oldPrice: null,
    image: img05,
  },
  {
    id: uuid(),
    title: "Title 06",
    description: "Description 03",
    hot: false,
    sale: false,
    category: "dress",
    price: 63.85,
    oldPrice: null,
    image: img06,
  },
  {
    id: uuid(),
    title: "Title 07",
    description: "Description 03",
    hot: false,
    sale: false,
    category: "bag",
    price: 63.85,
    oldPrice: null,
    image: img07,
  },
  {
    id: uuid(),
    title: "Title 08",
    description: "Description 03",
    hot: false,
    sale: true,
    category: "dress",
    price: 48.35,
    oldPrice: 63.85,
    image: img08,
  },
  {
    id: uuid(),
    title: "Title 09",
    description: "Description 03",
    hot: false,
    sale: false,
    category: "watch",
    price: 63.85,
    oldPrice: null,
    image: img09,
  },
  {
    id: uuid(),
    title: "Title 10",
    description: "Description 03",
    hot: true,
    sale: false,
    category: "dress",
    price: 63.85,
    oldPrice: null,
    image: img11,
  },
  {
    id: uuid(),
    title: "Title 11",
    description: "Description 03",
    hot: false,
    sale: false,
    category: "shoes",
    price: 63.85,
    oldPrice: null,
    image: img12,
  },
  {
    id: uuid(),
    title: "Title 12",
    description: "Description 03",
    hot: false,
    sale: false,
    category: "watch",
    price: 63.85,
    oldPrice: null,
    image: img10,
  },
  {
    id: uuid(),
    title: "Title 13",
    description: "Description 03",
    hot: false,
    sale: false,
    category: "t-shirt",
    price: 63.85,
    oldPrice: null,
    image: img13,
  },
  {
    id: uuid(),
    title: "Title 14",
    description: "Description 03",
    hot: false,
    sale: false,
    category: "bag",
    price: 63.85,
    oldPrice: null,
    image: img14,
  },
  {
    id: uuid(),
    title: "Title 15",
    description: "Description 03",
    hot: false,
    sale: true,
    category: "pants",
    price: 45.85,
    oldPrice: 63.85,
    image: img15,
  },
  {
    id: uuid(),
    title: "Title 16",
    description: "Description 03",
    hot: false,
    sale: false,
    category: "glasses",
    price: 63.85,
    oldPrice: null,
    image: img16,
  },
  {
    id: uuid(),
    title: "Title 17",
    description: "Description 03",
    hot: false,
    sale: false,
    category: "dress",
    price: 63.85,
    oldPrice: null,
    image: img17,
  },
  {
    id: uuid(),
    title: "Title 18",
    description: "Description 03",
    hot: false,
    sale: false,
    category: "dress",
    price: 63.85,
    oldPrice: null,
    image: img18,
  },
  {
    id: uuid(),
    title: "Title 19",
    description: "Description 03",
    hot: false,
    sale: false,
    category: "dress",
    price: 63.85,
    oldPrice: null,
    image: img19,
  },
  {
    id: uuid(),
    title: "Title 20",
    description: "Description 03",
    hot: false,
    sale: false,
    category: "dress",
    price: 63.85,
    oldPrice: null,
    image: img20,
  },
];
